### PR TITLE
Return status code to error handler, making it much more useful

### PR DESCRIPTION
**Pull request by NovaRemitly**

### CODE REVIEW

**Comment by adeeshaek** [comment]
Hi Joshua,

That's a great idea! I need to get permission to submit to the repo from my
employer, so I won't be able to integrate it until tuesday.

Thanks!

Adeesha

**Comment by NovaRemitly** [comment]
Hi Adeesha,

Thanks for taking a look at this. Has there been any update from your employer?

Thanks!
Josh

**Comment by adeeshaek** [comment]
Hi Joshua,

They haven't got back to me yet; if they don't get back to me by the end of
the week, would you like to be the project admin, so you can make the
changes you would like to?

Adeesha

**Comment by NovaRemitly** [comment]
Sure, I would be okay with that.

**Pull request closed without merging**
